#!/bin/bash
set -x
# 
# globus debugging example
#

# config files
export GSI_AUTHZ_CONF=/home/tschopp/gsi-authz.conf
cat $GSI_AUTHZ_CONF
export GSI_PEP_CALLOUT_CONF=/home/tschopp/gsi-pep-callout.conf

# debug level (0-9)
#export GLOBUS_CALLOUT_DEBUG_LEVEL=5
#export GLOBUS_GSSAPI_DEBUG_LEVEL=5
export GSI_PEP_CALLOUT_DEBUG_LEVEL=0

# and start gridftp server
/usr/sbin/globus-gridftp-server -d 255 -p 9999 -debug
set +x
